agentId: "1000002"
secret: "FEONPjYvrJ67U63BW8E0czXL4jp17jf0f8P-8gjyYM0"
corid: "wwf3beef22f578387a"
contactSecret: "jYw-kCkdLmb8ox2BlxDt89q9jP4Zsn8BTU9IWP7ra6U"
currentEnv: brainPlatformDev
env:
  dev:
    "work.weixin.qq.com": "work.weixin.qq.com"
    "qyapi.weixin.qq.com": "qyapi.weixin.qq.com"
  test:
    "work.weixin.qq.com": "140.207.127.79"
    "qyapi.weixin.qq.com": "qyapi.weixin.qq.com"


  brainPlatformTest:
    "ijixin.com":  "192.168.1.103"
  brainPlatformDev:
    "ijixin.com": "47.103.47.170"


   
